# Generated by Django 4.1 on 2022-08-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_name_remove_event_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tg_sent',
            field=models.BooleanField(default=False),
        ),
    ]
