# Generated by Django 4.1 on 2022-08-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_event_tg_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField(null=True)),
                ('image', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=150)),
                ('source_url', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField()),
                ('tickers', models.CharField(max_length=50)),
                ('sentiment', models.CharField(max_length=50)),
                ('tg_sent', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
